name: Deploy application

run-name: ${{ github.actor }} is deploying project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Create remote folder
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              root@${{ secrets.SERVER_HOST }} \
              "mkdir -p /opt/ms-clinique-rabat/microservices"

  build-project:
    name: Build Spring Boot application
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Spring Boot project
        working-directory: springBoot
        run: |
          mvn clean package spring-boot:repackage -DskipTests
          ls -al target

      - name: Copy JAR to server
        run: |
          scp -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              springBoot/target/GestionClinique-0.0.1-SNAPSHOT.jar \
              root@${{ secrets.SERVER_HOST }}:/opt/ms-clinique-rabat/microservices/

  run-project:
    name: Run application on server
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Run application via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              root@${{ secrets.SERVER_HOST }} << 'EOF'
                set -e
                echo "SSH OK"
                mkdir -p /opt/ms-clinique-rabat/microservices
              EOF
        env:
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_USERPASSWORD: ${{ secrets.DATABASE_USERPASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
