name: Deploy Frontend - Clinique Rabat

run-name: ${{ github.actor }} deploys Clinique Rabat frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: website_Clinique_rabat
        run: npm install

      - name: Build frontend (Vite)
        working-directory: website_Clinique_rabat
        run: npm run build

      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/clinique-rabat/*
            sudo mkdir -p /var/www/clinique-rabat
            sudo chown -R www-data:www-data /var/www/clinique-rabat

      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: website_Clinique_rabat/dist/*
          target: /var/www/clinique-rabat
          overwrite: true


